apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ansible-templates
  description: Ansible-powered software templates
spec:
  targets:
    - ./provision-team-env/template.yaml
    - ./deploy-app/template.yaml
    - ./teardown-namespace/template.yaml
